name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

jobs:
  cabal:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['8.6', '8.8', '8.10', 'latest']
        # cabal: ['latest']
        os: [ubuntu-latest, macOS-latest, windows-latest]
        exclude:
          - os: macOS-latest
            ghc: 8.8
          - os: macOS-latest
            ghc: 8.6
          - os: windows-latest
            ghc: 8.8
          - os: windows-latest
            ghc: 8.6
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          # cabal-version: ${{ matrix.cabal }} -- Omitted, but defaults to 'latest'
      - name: Build
        run: |
          cabal configure --enable-tests --enable-benchmarks --test-show-details=direct
          cabal build all --disable-optimization
      - name: Test
        run: |
          cabal test all

  stack:
    name: stack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          # ghc-version: 'latest'. Omitted, but defaults to 'latest'
          # cabal-version: 'latest'. Omitted, but defaults to 'latest'
          enable-stack: true
          # stack-version: 'latest'. Omitted, but defaults to 'latest'
      - name: Build
        run: |
          stack build --system-ghc --test --bench --fast --no-run-tests --no-run-benchmarks
      - name: Test
        run: |
          stack test --system-ghc
