name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

jobs:
  cabal:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['8.6.5', '8.8.3', 'latest']
        # cabal: ['latest']
        os: [ubuntu-latest, macOS-latest, windows-latest]
        exclude:
          - os: macOS-latest
            ghc: 8.8.3
          - os: macOS-latest
            ghc: 8.6.5
          - os: windows-latest
            ghc: 8.8.3
          - os: windows-latest
            ghc: 8.6.5
    name: Haskell GHC ${{ matrix.ghc }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          # cabal-version: 'latest'. Omitted, but defaults to 'latest'
          # cabal-version: ${{ matrix.cabal }}
      - name: Build
        run: |
          cabal configure --enable-tests --enable-benchmarks --test-show-details=direct
          cabal build all --disable-optimization
      - name: Test
        run: |
          cabal test all

  stack:
    name: stack / ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack: ["latest"]
        ghc:
          - "8.8.3"
          - "latest"

    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          # cabal-version: 'latest'. Omitted, but defaults to 'latest'
          enable-stack: true
          # stack-version: ${{ matrix.stack }}
          stack-version: 'latest'
      - name: Build
        run: |
          stack build --system-ghc --test --bench --fast --no-run-tests --no-run-benchmarks
      - name: Test
        run: |
          stack test --system-ghc
